project_id = "nlxlvllptilajgwiqwqh"

[functions.generate-response]
verify_jwt = false

[functions.process-pdf]
verify_jwt = false

[functions.purge-vectors]
verify_jwt = false

[functions.reset-knowledge]
verify_jwt = false
