// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlxlvllptilajgwiqwqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5seGx2bGxwdGlsYWpnd2lxd3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzY0MDUsImV4cCI6MjA3MDg1MjQwNX0.xhATGvk0v66WW_MQz8jXb2axjW60R_E8p_rwq1vzfDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});