// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Temporarily hardcoding to bypass environment variable issues
const SUPABASE_URL = "https://jmhfaqlxketpqrxvuejv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptaGZhcWx4a2V0cHFyeHZ1ZWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTgwOTQsImV4cCI6MjA3MDg3NDA5NH0.joG1Ek-T-VjsoTqR_KrIhsJTOmJUg9HVOToEvwxfwGE";

// Debug logging
console.log('Supabase URL:', SUPABASE_URL);
console.log('Supabase Key (first 20 chars):', SUPABASE_PUBLISHABLE_KEY.substring(0, 20));

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});